name: CI/CD for RssSystem

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean bootWar

      - name: Debug build output
        run: ls -l build/libs

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: egzaminator
          path: build/libs/egzaminator.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: egzaminator
          path: build/libs

      - name: Debug downloaded artifact
        run: ls -l /home/runner/work/egzaminator-backend/egzaminator-backend

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Cleanup old WARs
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
          sudo rm -f /opt/tomcat/webapps/egzaminator_app.war
          EOF

      - name: Deploy to Ubuntu Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '23'
          source: build/libs/*.war
          target: /opt/tomcat/webapps/
          strip_components: 2

      - name: Restart Tomcat
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
          sudo /opt/tomcat/bin/shutdown.sh
          sudo /opt/tomcat/bin/startup.sh
          EOF
